image: atlassian/default-image:2

pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - docker build -t $API_IMAGE_NAME:$BITBUCKET_COMMIT .
          - docker push $API_IMAGE_NAME:$BITBUCKET_COMMIT
