image: code.putech.ir:5000/chiro-base-api
definitions:
  services:
    redis:
      image: redis
    postgres:
      image: postgres
      variables:
        POSTGRES_USER: default
        POSTGRES_PASSWORD: "123456"
        POSTGRES_DB: default
  caches:
    vendor: /app/vendor

pipelines:
  default:
    - step:
        services:
          - docker
          - redis
          - postgres
        caches:
          - vendor
        script:
          - composer install
          - export DB_CONNECTION=pgsql
          - export DB_HOST=localhost
          - export DB_PORT=5432
          - export DB_DATABASE=default
          - export DB_USERNAME=default
          - export DB_PASSWORD=123456
          - cp .env.example .env
          - php artisan key:generate
          - php artisan migrate --seed
          - ./vendor/bin/phpunit
          - docker build -t $API_IMAGE_NAME .
          - docker push $API_IMAGE_NAME
