image: code.putech.ir:5000/chiro-base-api
definitions:
  services:
    redis:
      image: redis
    postgres:
      image: postgres
      variables:
        POSTGRES_USER: default
        POSTGRES_PASSWORD: "123456"
        POSTGRES_DB: default
  caches:
    laravel: vendor

pipelines:
  default:
    - step:
        name: prepare
        caches:
          - laravel
        script:
          - composer install
          - composer dump-autoload
    - step:
        name: test
        services:
          - redis
          - postgres
        caches:
          - laravel
        script:
          - export DB_CONNECTION=pgsql
          - export DB_HOST=localhost
          - export DB_PORT=5c432
          - export DB_DATABASE=default
          - export DB_USERNAME=default
          - export DB_PASSWORD=123456
          - cp .env.example .env
          - php artisan key:generate
          - php artisan migrate --seed
          - ./vendor/bin/phpunit --testdox
  branches:
    master:
      - step:
          name: build
          services:
            - docker
          caches:
            - laravel
          script:
            - docker build -t $API_IMAGE_NAME .
            - docker push $API_IMAGE_NAME
