version: "3"
services:
  # api:
  #   build: ./
  #   volumes:
  #     - ./.docker/php/www.conf:/etc/php/7.3/php-fpm.d/www.conf
  #     - ./:/app

  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./.docker/nginx/index.php:/app/public/index.php
  #   ports:
  #     - 8080:80

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=123456
      - MYSQL_USER=default
      - MYSQL_DATABASE=default
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
