version: "3"
services:
  api:
    image: 2hamed/chiro-api
    volumes:
      - storage:/app/public/static
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=default
      - DB_USERNAME=default
      - DB_PASSWORD=123456
      - REDIS_HOST=redis

  nginx:
    image: 2hamed/chiro-nginx:latest
    volumes:
      - storage:/app/public/static
    ports:
      - 8080:80

  redis:
    image: redis

  db:
    image: postgres
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=default
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
  storage:
