version: "3"
services:
  # api:
  #   build: ./
  #   volumes:
  #     - ./.docker/php/www.conf:/etc/php/7.3/php-fpm.d/www.conf
  #     - ./:/app

  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./.docker/nginx/index.php:/app/public/index.php
  #   ports:
  #     - 8080:80

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=default
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456

volumes:
  dbdata:
